// <auto-generated />
namespace Chinook.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Base));
        
        string IMigrationMetadata.Id
        {
            get { return "201304251009083_Base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
